######### read in data etc

# load required packages
package_list <- c("plyr", "tidyverse", "janitor", "gridExtra", "ggpubr", "readxl", "cowplot", "scales", "stats", "devtools", "metabom8", "shiny", "plotly", "svDialogs", "DataEditR", "htmlwidgets", "httr")
loaded_packages <- lapply(package_list, require, character.only = TRUE)
rm(loaded_packages, package_list)

# load custom functions from github
lipidomics_class_sum_function <- GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/ANPC_lipidomics_tools/functions/2021-LGW-lipidomics-class_sumR_function.r") %>% content(as = "text")
eval(parse(text = lipidomics_class_sum_function), envir = .GlobalEnv)
rm(lipidomics_class_sum_function)

dlg_message("Welcome to lipid exploreR! :-)", type = 'ok')

dlg_message("Please select your project folder", type = 'ok')

project_dir <- rstudioapi::selectDirectory() # save project directory root location
setwd(project_dir) # switch the project directory

#user input here for project name and user initials
temp_answer <- "blank"
if(exists("project_name") == TRUE){temp_answer <- dlgInput(paste("the project name is ", project_name, "is this correct?", sep=" "), "yes/no")$res}
while(temp_answer != "yes"){
project_name <- dlgInput("what is the name of the project? This must match the string in Filename", "example_project")$res
temp_answer <- dlgInput(paste("the project name is ", project_name, "is this correct?", sep=" "), "yes/no")$res
}

temp_answer <- "blank"
if(exists("user_name") == TRUE){temp_answer <- dlgInput(paste("the user is ", user_name, "is this correct?", sep=" "), "yes/no")$res}
while(temp_answer != "yes"){
  user_name <- dlgInput("Insert your initials", "example_initials")$res
  temp_answer <- dlgInput(paste("the user is ", user_name, "is this correct?", sep=" "), "yes/no")$res
}


# read in master data
temp_answer <- "blank"
while(temp_answer != "yes" & temp_answer != "no"){
temp_answer <- dlgInput("Do you want to read in new data?", "yes/no")$res
}
if(temp_answer == "yes"){dlg_message("Open metabolite data csv by selecting the CSV generated by the SkylineR data processing script", type = 'ok')
  master_lipid_data <- read_csv(file = file.choose(.)) %>% clean_names %>% rename(lipid_target = peptide, lipid_class = protein)
}

sampleID <- master_lipid_data$replicate %>% unique() # create list of sample IDs
lipid <- master_lipid_data$lipid_target %>% unique() # create list of lipid targets
lipid_class_list <- master_lipid_data %>% select(lipid_class) %>% unique()

individual_lipid_data <- apply(as_tibble(lipid), 1, function(lip){
  #browser()
  sampleID <- master_lipid_data$replicate %>% unique() %>% as_tibble() # create list of sample IDs
  temp_data <- master_lipid_data %>% filter(lipid_target == lip) %>% select(replicate, area)
  colnames(temp_data) <- c("value", lip) 
  temp_data <- left_join(sampleID, temp_data, by = "value") 
  #temp_data <- temp_data %>% select(lip)
}) %>% bind_cols() %>% select(all_of(lipid)) %>% add_column(sampleID, .before = 1)

plate_id <- str_extract(individual_lipid_data$sampleID, "PLIP.*")
plate_id <- substr(plate_id, 0,15)
plate_id <- paste(plate_id, sub(".*\\_", "", individual_lipid_data$sampleID), sep="_")


individual_lipid_data <- individual_lipid_data %>% add_column(plate_id, .before = 2) %>% arrange(plate_id)
individual_lipid_data <- individual_lipid_data %>% filter(!grepl("conditioning", sampleID))
class_lipid_data <- create_lipid_class_data_summed(individual_lipid_data)



##################### Run the rest of the QC exploreR sub-scripts from here

# SIL check - sums the intensity of all stable isotope labeled internal standards, visualizes the result. If IS have been added correctly should be within x deviations from the median. Allows visualization of outliers
summed_SIL_checkR_script <- GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/ANPC_lipidomics_tools/scripts/2021-LGW-lipidomics-summed_SIL_checkR_script.r") %>% 
  content(as = "text")
eval(parse(text = summed_SIL_checkR_script), envir = .GlobalEnv)
rm(summed_SIL_checkR_script)

# TIC check - sums the intensity of all target lipids, visualizes the result. If sample has been added to the well correctly should be within x deviations from the median. Allows visualization of outliers.
summed_TIC_checkR_script <- GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/ANPC_lipidomics_tools/scripts/2021-LGW-lipidomics-summed_TIC_checkR_script.R") %>% 
  content(as = "text")
eval(parse(text = summed_TIC_checkR_script), envir = .GlobalEnv)
rm(summed_TIC_checkR_script)

#intensity threshold filter
intensity_threshold_checkR_script <- GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/ANPC_lipidomics_tools/scripts/2021-LGW-lipidomics-intensity_threshold_checkR_script.R") %>% content(as = "text")
eval(parse(text = intensity_threshold_checkR_script), envir = .GlobalEnv)
rm(intensity_threshold_checkR_script)

# Review individual SIL internal standards 
# Create target lipid to stable isotope ratio internal standard and evaluate them in the pooled QC. Here we use Long Term Reference pool
LTR_SIL_checkR_script <- GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/ANPC_lipidomics_tools/scripts/2021-LGW-lipidomics-internal_standard_normaliseR.r") %>% 
  content(as = "text")
eval(parse(text = LTR_SIL_checkR_script), envir = .GlobalEnv)
rm(LTR_SIL_checkR_script)

# Produce a PCA to QC data. Allowws for visualization of LTR sample clustering
PCA_QC_script <- GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/ANPC_lipidomics_tools/scripts/2021-LGW-lipidomics-PCA_QC_checkR_script.r") %>% content(as = "text")
eval(parse(text = PCA_QC_script), envir = .GlobalEnv)
rm(PCA_QC_script)




