---
title: "SCIEX LIPIDOMICS NOTEBOOK"
output:
  html_document:
    df_print: paged
---

This is an R Notebook designed to help with the processing of lipidomic data generated using the ANPC sciex platform. To run this script you need the following:

1. Create an r-studio project.
  -> open rstudio then click:
    
      File  -> New Project 
              -> New Directory 
                -> New Project 
                  -> browse - navigate to desired location of project 
                    -> type in new project name (e.g. COVID lipidomics)

2. Navigate to the new project in Windows Explorer (or MacOS finder) and set it up with the following files in specific subfolders:
  
      data
      
        -> a folder called "data" containing the following files:
      
        -> File 1:  a ".txt" file containing the metadata. 
                    the filename must contain the text string "sampleDescriptionList"                                 Note - for default ANPC projects this file will be generated by the lims.
      
        -> File 2:  a ".csv" file generated by Skyline MS data processing software using the                          ANPC lipidomics data pre-processing notebook. 
                    The file must contain the text string "export_metabolite_data"
  
      scripts
  
        -> a folder called "scripts" containing the following files:
      
        -> Script 1:  "ANPC_sciex_lipidomics_functions.r" availible from Luke Whiley github. 
                      See Luke for details.
  
  
      plots
  
        -> an empty folder used to store exported plots
      

--------------------------------------------------------------------------------------------------

Notebook Section 1 
Load required packages and functions that are required throughout the notebook

```{r, libraries used,  echo = FALSE, warning=FALSE, message=FALSE, fig.height=6, fig.width=10}
# libraries
package_list <- c("plyr", "tidyverse", "janitor", "gridExtra", "ggpubr", "readxl", "cowplot", "scales", "devtools", "metabom8", "shiny", "plotly", "svDialogs", "DataEditR", "htmlwidgets")
lapply(package_list, require, character.only = TRUE)
source('scripts/LGW_lipidomics_fuctions.R')

#user input here for project name and user initials

project_name <- dlgInput("what is the name of the project? This must match the string in Filename", "example_project")$res
user_name <- dlgInput("Insert your initials", "example_initials")$res

# read in master data
dlg_message("Open metabolite data csv by selecting the CSV generated by the Skyline data processing", type = 'ok')

master_metabolite_data <- read_csv(file = file.choose(.))

dlg_message("Open metabolite metadata by selecting the project SampleDescriptionList.txt generated by the LIMS", type = 'ok')
master_metadata <- read_delim(file = file.choose(.), delim = "\t")

sampleID <- master_metabolite_data %>% select(contains(project_name)) %>% colnames() # create list of sample IDs
lipid <- master_metabolite_data$lipid_target # create list of lipid targets
lipid_family <- master_metabolite_data %>% select(lipid_class) %>% unique()
metabolite_data <- master_metabolite_data %>% select(contains(project_name)) %>% t() %>% as_tibble(.name_repair = "universal") %>% add_column(sampleID, .before =1)
colnames(metabolite_data) <- c("sampleID", lipid)
#replace sample ID in metabolite data with equivilent from master_metadata to make combining work
for(idx_sID in 1:nrow(master_metadata)){
  sID <- master_metadata$sampleID[idx_sID]
  metabolite_data$sampleID[grep(sID, metabolite_data$sampleID)] <- sID
}

combined_data <- right_join(master_metadata, metabolite_data, by = "sampleID") 
analysis_data <- combined_data

dlg_message("The next step is to prepare the data for the PCA models", type = 'ok')

filter_terms <- dlgInput("Enter the filter critera seperated by a comma. Remember sampleID is automatically selected.", "example: class, sex, anpc_timepoint")$res %>% strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")

filter_column_check <- which(colnames(analysis_data) == filter_terms)

while(length(filter_column_check) != length(filter_terms)){
  filter_terms <- dlgInput("Columns not found. Are you sure the spelling matches? Re-enter filter criteria here.", "example: class, sex, anpc_timepoint")$res %>% strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")
  filter_column_check <- which(colnames(analysis_data) == filter_terms)
}

training_template <- analysis_data %>% select(c("sampleID", all_of(filter_terms))) %>% as.data.frame()
training_template$training <- FALSE

dlg_message("Select the training set samples in the next window. Remeber to press the Sync button before pressing the Done button", type = 'ok')

training_template_edited <- data_edit(training_template,
          viewer = "dialog")
training_template_edited <- training_template_edited %>% filter(training == TRUE) 

#create final training set data from analysis data
training_analysis_data <- analysis_data %>% filter(sampleID %in% training_template_edited$sampleID)

dlg_message("The script will now create lipid family data", type = 'ok') 

# create training set data for summed lipid families
family_data <- create_family_data_summed(training_analysis_data)

family_training_analysis_data <- family_data %>% 
  add_column(select(training_analysis_data, sampleID), select(training_analysis_data, all_of(filter_terms)), .before = 1)

#user input - plot options should be entered here

class_selection <- dlgInput("What column should be used for colouring multivariate plots?", paste("example:", filter_terms))$res
class_name <- training_analysis_data %>% select(class_selection) %>% unique() %>% unlist() %>% paste()
number_of_classes <- training_analysis_data %>% select(class_selection) %>% unique() %>% nrow()

plot_colours <- dlgInput(paste("To colour multivariate plots by", class_selection, "please enter", number_of_classes, "colour choices"), "example: #999999,  #56B4E9, firebrick3")$res %>%  strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")

while(length(plot_colours) != number_of_classes){
  plot_colours <- dlgInput(paste("You have not selected enough colours please enter", number_of_classes, "colour choices"), "example: #999999,  #56B4E9")$res %>%  strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")
}

label_sampleIDs <- dlgInput("Do you want each sample to be labelled with its ID on the plot? TRUE or FALSE", "example: TRUE")$res

##################################################################################################################################
# create a PCA here
pca_list <- lipids_pca(training_analysis_data, family_training_analysis_data, class_selection)
saveWidget(pca_list[[11]], file = "tmp.html")
browseURL("tmp.html")

remove_samples <- dlgInput("Do you want to remove any outlier samples from the analysis?", "yes/no")$res

while(remove_samples == "yes"){
  training_template_edited <- data_edit(training_template_edited,
          viewer = "dialog")
  training_template_edited <- training_template_edited %>% filter(training == TRUE)
  training_analysis_data <- analysis_data %>% filter(sampleID %in% training_template_edited$sampleID)
  dlg_message("The script will now create lipid family data", type = 'ok') 
  family_data <- create_family_data_summed(training_analysis_data)
  family_training_analysis_data <- family_data %>% 
  add_column(select(training_analysis_data, sampleID), select(training_analysis_data, all_of(filter_terms)), .before = 1)

pca_list <- lipids_pca(training_analysis_data, family_training_analysis_data, class_selection)
saveWidget(pca_list[[11]], file = "tmp.html")
browseURL("tmp.html")
remove_samples <- dlgInput("Do you want to remove any outlier samples from the analysis?", "yes/no")$res
}

##################################################################################################################################
# create OPLS-DA

dlg_message("The next step is to prepare the data for the OPLS-DA models", type = 'ok')

filter_terms <- dlgInput("Enter the filter critera seperated by a comma. Remember sampleID is automatically selected.", "example: class, sex, anpc_timepoint")$res %>% strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")

filter_column_check <- which(colnames(analysis_data) == filter_terms)

while(length(filter_column_check) != length(filter_terms)){
  filter_terms <- dlgInput("Columns not found. Are you sure the spelling matches? Re-enter filter criteria here.", "example: class, sex, anpc_timepoint")$res %>% strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")
  filter_column_check <- which(colnames(analysis_data) == filter_terms)
}

training_template <- analysis_data %>% select(c("sampleID", all_of(filter_terms))) %>% as.data.frame()
training_template$training <- FALSE

dlg_message("Select the training set samples in the next window. Remeber to press the Sync button before pressing the Done button", type = 'ok')

training_template_edited <- data_edit(training_template,
          viewer = "dialog")
training_template_edited <- training_template_edited %>% filter(training == TRUE) 

#create final training set data from analysis data
training_analysis_data <- analysis_data %>% filter(sampleID %in% training_template_edited$sampleID)

dlg_message("The script will now create lipid family data", type = 'ok') 

# create training set data for summed lipid families
family_data <- create_family_data_summed(training_analysis_data)

family_training_analysis_data <- family_data %>% 
  add_column(select(training_analysis_data, sampleID), select(training_analysis_data, all_of(filter_terms)), .before = 1)

#user input - plot options should be entered here

class_selection <- dlgInput("What column should be used for colouring multivariate plots?", paste("example:", filter_terms))$res
class_name <- training_analysis_data %>% select(class_selection) %>% unique() %>% unlist() %>% paste()
number_of_classes <- training_analysis_data %>% select(class_selection) %>% unique() %>% nrow()

plot_colours <- dlgInput(paste("To colour multivariate plots by", class_selection, "please enter", number_of_classes, "colour choices"), "example: #999999,  #56B4E9, firebrick3")$res %>%  strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")

while(length(plot_colours) != number_of_classes){
  plot_colours <- dlgInput(paste("You have not selected enough colours please enter", number_of_classes, "colour choices"), "example: #999999,  #56B4E9")$res %>%  strsplit(split = ",") %>% unlist() %>% c() %>% str_replace_all(" ", "")
}

label_sampleIDs <- dlgInput("Do you want each sample to be labelled with its ID on the plot? TRUE or FALSE", "example: TRUE")$res

##################################################################################################################################
# create a OPLS-DA here
opls_list <- lipids_opls(family_training_analysis_data, training_analysis_data, class_selection)
saveWidget(pca_list[[11]], file = "tmp.html")
browseURL("tmp.html")

remove_samples <- dlgInput("Do you want to remove any outlier samples from the analysis?", "yes/no")$res

while(remove_samples == "yes"){
  training_template_edited <- data_edit(training_template_edited,
          viewer = "dialog")
  training_template_edited <- training_template_edited %>% filter(training == TRUE)
  training_analysis_data <- analysis_data %>% filter(sampleID %in% training_template_edited$sampleID)
  dlg_message("The script will now create lipid family data", type = 'ok') 
  family_data <- create_family_data_summed(training_analysis_data)
  family_training_analysis_data <- family_data %>% 
  add_column(select(training_analysis_data, sampleID), select(training_analysis_data, all_of(filter_terms)), .before = 1)

pca_list <- lipids_pca(training_analysis_data, family_training_analysis_data, class_selection)
saveWidget(pca_list[[11]], file = "tmp.html")
browseURL("tmp.html")
remove_samples <- dlgInput("Do you want to remove any outlier samples from the analysis?", "yes/no")$res
}






```






