######### read in data etc

package_list <- c("plyr", "tidyverse", "janitor", "gridExtra", "ggpubr", "readxl", "cowplot", "scales", "devtools", "metabom8", "shiny", "plotly", "svDialogs", "DataEditR", "htmlwidgets", "httr")
loaded_packages <- lapply(package_list, require, character.only = TRUE)
rm(loaded_packages)

dlg_message("Welcome to lipid exploreR! :-)", type = 'ok')

dlg_message("Please select your project folder", type = 'ok')

project_dir <- rstudioapi::selectDirectory() # save project directory root location
setwd(project_dir)# switch the project directory

#user input here for project name and user initials
temp_answer <- "blank"
if(exists("project_name") == TRUE){temp_answer <- dlgInput(paste("the project name is ", project_name, "is this correct?", sep=" "), "yes/no")$res}
while(temp_answer != "yes"){
project_name <- dlgInput("what is the name of the project? This must match the string in Filename", "example_project")$res
temp_answer <- dlgInput(paste("the project name is ", project_name, "is this correct?", sep=" "), "yes/no")$res
}

temp_answer <- "blank"
if(exists("user_name") == TRUE){temp_answer <- dlgInput(paste("the user is ", user_name, "is this correct?", sep=" "), "yes/no")$res}
while(temp_answer != "yes"){
  user_name <- dlgInput("Insert your initials", "example_initials")$res
  temp_answer <- dlgInput(paste("the user is ", user_name, "is this correct?", sep=" "), "yes/no")$res
}


# read in master data
temp_answer <- "blank"
while(temp_answer != "yes" & temp_answer != "no"){
temp_answer <- dlgInput("Do you want to read in new data?", "yes/no")$res
}
if(temp_answer == "yes"){dlg_message("Open metabolite data csv by selecting the CSV generated by the SkylineR data processing script", type = 'ok')
  master_lipid_data <- read_csv(file = file.choose(.)) %>% clean_names %>% rename(lipid_target = peptide, lipid_class = protein)
}

sampleID <- master_lipid_data$replicate %>% unique() # create list of sample IDs
lipid <- master_lipid_data$lipid_target %>% unique() # create list of lipid targets
lipid_class_list <- master_lipid_data %>% select(lipid_class) %>% unique()

individual_lipid_data <- apply(as_tibble(lipid), 1, function(lip){
  #browser()
  sampleID <- master_lipid_data$replicate %>% unique() %>% as_tibble() # create list of sample IDs
  temp_data <- master_lipid_data %>% filter(lipid_target == lip) %>% select(replicate, area)
  colnames(temp_data) <- c("value", lip) 
  temp_data <- left_join(sampleID, temp_data, by = "value") 
  #temp_data <- temp_data %>% select(lip)
}) %>% bind_cols() %>% select(all_of(lipid)) %>% add_column(sampleID, .before = 1)

plate_id <- str_extract(individual_lipid_data$sampleID, "PLIP.*")
plate_id <- substr(plate_id, 0,15)
plate_id <- paste(plate_id, sub(".*\\_", "", individual_lipid_data$sampleID), sep="_")

individual_lipid_data <- individual_lipid_data %>% add_column(plate_id, .before = 2) %>% arrange(plate_id)
class_lipid_data <- create_lipid_class_data_summed(individual_lipid_data)





