######### read in data etc

package_list <- c("plyr", "tidyverse", "janitor", "gridExtra", "ggpubr", "readxl", "cowplot", "scales", "devtools", "metabom8", "shiny", "plotly", "svDialogs", "DataEditR", "htmlwidgets", "httr")
loaded_packages <- lapply(package_list, require, character.only = TRUE)
rm(loaded_packages)

dlg_message("Welcome to lipid exploreR! :-)", type = 'ok')

dlg_message("Please select your project folder", type = 'ok')

project_dir <- rstudioapi::selectDirectory() # save project directory root location
setwd(project_dir)# switch the project directory

#user input here for project name and user initials
if(exists("project_name") != TRUE){project_name <- dlgInput("what is the name of the project? This must match the string in Filename", "example_project")$res}
if(exists("user_name") != TRUE){user_name <- dlgInput("Insert your initials", "example_initials")$res}

# read in master data
temp_answer <- dlgInput("Do you want to read in new data?", "yes/no")$res
if(temp_answer == "yes"){dlg_message("Open metabolite data csv by selecting the CSV generated by the SkylineR data processing script", type = 'ok')
  master_lipid_data <- read_csv(file = file.choose(.)) %>% clean_names %>% rename(lipid_target = peptide, lipid_class = protein)
}

sampleID <- master_lipid_data$replicate %>% unique() # create list of sample IDs
lipid <- master_lipid_data$lipid_target %>% unique() # create list of lipid targets
lipid_class_list <- master_lipid_data %>% select(lipid_class) %>% unique()

individual_lipid_data <- apply(as_tibble(lipid), 1, function(lip){
  #browser()
  sampleID <- master_lipid_data$replicate %>% unique() %>% as_tibble() # create list of sample IDs
  temp_data <- master_lipid_data %>% filter(lipid_target == lip) %>% select(replicate, area)
  colnames(temp_data) <- c("value", lip) 
  temp_data <- left_join(sampleID, temp_data, by = "value") 
  #temp_data <- temp_data %>% select(lip)
}) %>% bind_cols() %>% select(all_of(lipid)) %>% add_column(sampleID, .before = 1)

plate_id <- str_extract(individual_lipid_data$sampleID, "PLIP.*")
plate_id <- substr(plate_id, 0,15)
plate_id <- paste(plate_id, sub(".*\\_", "", individual_lipid_data$sampleID), sep="_")

individual_lipid_data <- individual_lipid_data %>% add_column(plate_id, .before = 2) %>% arrange(plate_id)
class_lipid_data <- create_lipid_class_data_summed(individual_lipid_data)


###################################
# SIL check
##################################

dlg_message("Internal standard check. This next step will assess the internal standards accross all of the samples. If internal standards have been incorrectly added the summed signal intensity will be too low/high.", type = 'ok')

total_summed_sil <- apply(individual_lipid_data %>% select(sampleID), 1, function(summedSIL){
  temp_data <- individual_lipid_data %>% filter(sampleID == summedSIL) %>% select(-sampleID) %>% select(contains("SIL")) %>% rowSums(na.rm = TRUE)
}) %>% c() %>% as_tibble() %>%  add_column(individual_lipid_data$sampleID, .before = 1) %>% 
  rename(SIL_TIC = value, sampleID = "individual_lipid_data$sampleID")

plateid <- str_extract(individual_lipid_data$sampleID, "PLIP.*")
plateid <- substr(plateid, 0,15)
plate_id <- paste(plateid, sub(".*\\_", "", individual_lipid_data$sampleID), sep="_")

total_summed_sil <- total_summed_sil %>% add_column(plate_id, .before = 2) %>% arrange(plate_id)
total_summed_sil$sample_idx <- c(1:nrow(total_summed_sil))
total_summed_sil$LOG_SIL_TIC <- log(total_summed_sil$SIL_TIC)

#flag samples with SIL x standard deviations below mean
temp_answer <- dlgInput("What do you wish to set for the fail cut off filter.  x number of standard deviations from the mean", "e.g.   x = 2")$res

mean_sil_tic <- mean(total_summed_sil$SIL_TIC)
sd_sil_tic <- sd(total_summed_sil$SIL_TIC)
sil_sd_mean_cut_off_lower <- mean_sil_tic - (as.numeric(temp_answer)*sd_sil_tic)
sil_sd_mean_cut_off_upper <- mean_sil_tic + (as.numeric(temp_answer)*sd_sil_tic)

sil_qc_fail <- total_summed_sil$sampleID[which(total_summed_sil$SIL_TIC < sil_sd_mean_cut_off_lower | total_summed_sil$SIL_TIC > sil_sd_mean_cut_off_upper)] %>% as_tibble %>% rename(sampleID = value)
sil_qc_fail$fail_point <- "sil"

#sil_qc_fail
temp_answer <- dlgInput(paste(nrow(sil_qc_fail), "sample FAILED the SIL QC check.  Do you want to remove failed samples?"), "yes/no")$res
if(temp_answer == "yes"){individual_lipid_data_sil_filtered <- individual_lipid_data %>% filter(!sampleID %in% sil_qc_fail$sampleID)}

#visualise for reports
total_summed_sil$removed <- "pass_qc"
total_summed_sil$removed[total_summed_sil$sampleID %in% sil_qc_fail$sampleID] <- "removed"

p <- plot_ly(type = "scatter", total_summed_sil, x = ~sample_idx, y = ~LOG_SIL_TIC, text = ~sampleID, color = ~removed, colors = c("lightblue3", "red"))

plate_number <- unique(plate_id) %>% substr(14,14) %>% unique()
plate_idx <- lapply(unique(plateid), function(plateID){grep(plateID, total_summed_sil$sampleID)[1]}) %>% unlist()
for (idx_line in 2:length(plate_idx)){
  p <- add_trace(p, x = plate_idx[idx_line], type = 'scatter', mode = 'lines', color = paste("plate_", plate_number[idx_line], sep=""), line = list(color = "grey", dash = "dash"), showlegend = FALSE)
}
p <- add_trace(p, y = log(sil_sd_mean_cut_off_lower), type = 'scatter', mode = 'lines', color = "SIL QC threshold", line = list(color = "red", dash = "dash"))
p <- add_trace(p, y = log(sil_sd_mean_cut_off_upper), type = 'scatter', mode = 'lines', color = "SIL QC threshold", line = list(color = "red", dash = "dash"));p

sil_check_p <- p
dir.create(paste(project_dir, "/html_files", sep=""))
saveWidget(sil_check_p, file = paste("/html_files/",project_name, "_", user_name, "_SIL_check_plot.html", sep=""))
browseURL(paste("/html_files/",project_name, "_", user_name, "_SIL_check_plot.html", sep=""))


