---
title: "SCIEX LIPIDOMICS NOTEBOOK"
output: LIPIDOMICS RESULTS
---

This is an R Notebook designed to help with the processing of lipidomic data generated using the ANPC sciex platform. To run this script you need the following:

1. an r project parent folder containing the following files in specific subfolders:
  
  -> data
  
    --> a folder containing the following files:
  
    --> file 1: a .txt file containing the metadata. File must contain the text string "sampleDescriptionList"                 Note - for default ANPC projects this file will be generated by Julien.
        
    --> file 2: a csv file generated by Skyline MS data processing software using the ANPC lipidomics data                      pre-processing notebook. The file must be a csv and contain the text string 
                 "export_metabolite_data".
  
  -> scripts
  
    --> a folder containing the following r scritps:
    
    --> script 1: "ANPC_sciex_lipidomics_functions.r" availible from Luke Whiley github. See Luke for details.
  
  
  -> plots
  
      --> empty folder used for the export of plots
      





```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

