---
title: "LGW - Metabolomice data processing"
output: html_notebook
---

This notebook can be used to visualise metabolomics data using both univariate and multivariate approaches. 

Section 1 - Load libraries

```{r, libraries used,  echo = FALSE, warning=FALSE}
library(plyr)
library(scales)
library(rstatix)
library(readxl)
library(tidyverse)
library(httr)
library(dunn.test)

parent_path <- paste(getwd())
```


Section 2 - Install custom functions from LGW github respository

```{r, }
# Source R script from Github
# LGW boxplots
script <-GET(url = "https://raw.githubusercontent.com/lukewhiley/metabolomics_code/main/lgw_boxplots.r",
             authenticate("luke.whiley@murdoch.edu.au", "cda3533bb0a8248333824bd91029b48c367164d4"),
             accept("application/vnd.github.v3.raw")) %>% content(as = "text")
eval(parse(text = script), envir = .GlobalEnv)
rm(script)
```

Section 3 - What are the data files called?

```{r}
name_of_data_file <- ""
name_of_metadata_file <- ""
```


Section 4 - read in the data

```{r}
name_of_data_file <- ""
name_of_metadata_file <- ""
```

